//! Helper for the agent-spawn site (EMD-27) to inject hook
//! coordinates into the child process's env. Names match the
//! Electron build's contract so embedded plugin scripts
//! (`pi-emdash-extension.ts`, `opencode-notifications-plugin.js`)
//! and the user-configured hook commands generated by
//! `hook_config` (EMD-26) reference the same variables.

use std::collections::HashMap;

/// Inject the running hook server's `port` + `token` + the current
/// child's `pty_id` into `env`. `pty_id` carries the
/// provider:conversation routing key used by the hook server to
/// look up the originating task and is what the embedded plugin
/// scripts forward as `X-Emdash-Pty-Id`.
pub fn inject_hook_env_into(
    env: &mut HashMap<String, String>,
    port: u16,
    token: &str,
    pty_id: &str,
) {
    env.insert("EMDASH_HOOK_PORT".to_string(), port.to_string());
    env.insert("EMDASH_HOOK_TOKEN".to_string(), token.to_string());
    env.insert("EMDASH_PTY_ID".to_string(), pty_id.to_string());
    // Convenience aggregate — some agents accept a single URL.
    env.insert(
        "EMDASH_HOOK_URL".to_string(),
        format!("http://127.0.0.1:{port}/hook"),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn injects_all_four_vars() {
        let mut env = HashMap::new();
        inject_hook_env_into(&mut env, 12345, "abc-token", "claude:conv-1");
        assert_eq!(env.get("EMDASH_HOOK_PORT").unwrap(), "12345");
        assert_eq!(env.get("EMDASH_HOOK_TOKEN").unwrap(), "abc-token");
        assert_eq!(env.get("EMDASH_PTY_ID").unwrap(), "claude:conv-1");
        assert_eq!(
            env.get("EMDASH_HOOK_URL").unwrap(),
            "http://127.0.0.1:12345/hook"
        );
    }

    #[test]
    fn does_not_clobber_unrelated_keys() {
        let mut env = HashMap::new();
        env.insert("PATH".into(), "/usr/bin".into());
        inject_hook_env_into(&mut env, 1, "t", "p:c");
        assert_eq!(env.get("PATH").unwrap(), "/usr/bin");
    }
}
