// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  Login-shell `$PATH` captured at app startup. OnceLock-cached. */
	getPath: () => __TAURI_INVOKE<string>("get_path"),
	setSecret: (key: string, value: string) => typedError<null, SecretsCommandError>(__TAURI_INVOKE("set_secret", { key, value })),
	getSecret: (key: string) => typedError<string | null, SecretsCommandError>(__TAURI_INVOKE("get_secret", { key })),
	ptySpawn: (opts: SpawnOptions, onData: Channel<number[]>) => typedError<PtyId, PtyError>(__TAURI_INVOKE("pty_spawn", { opts, onData })),
	ptyWrite: (id: PtyId, bytes: number[]) => typedError<null, PtyError>(__TAURI_INVOKE("pty_write", { id, bytes })),
	ptyResize: (id: PtyId, size: PtySize) => typedError<null, PtyError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: PtyId) => typedError<null, PtyError>(__TAURI_INVOKE("pty_kill", { id })),
	subscribeUiMutations: (subId: string, onEvent: Channel<UiMutationEvent>) => typedError<null, null>(__TAURI_INVOKE("subscribe_ui_mutations", { subId, onEvent })),
	unsubscribeUiMutations: (subId: string) => typedError<null, null>(__TAURI_INVOKE("unsubscribe_ui_mutations", { subId })),
	projectsList: () => typedError<Project[], ProjectsCommandError>(__TAURI_INVOKE("projects_list")),
	projectsAdd: (path: string) => typedError<Project, ProjectsCommandError>(__TAURI_INVOKE("projects_add", { path })),
	projectsRemove: (id: string) => typedError<null, ProjectsCommandError>(__TAURI_INVOKE("projects_remove", { id })),
};

/* Types */
/**
 *  Renderer-visible projection of one classified hook event.
 *  `task_id` / `project_id` are filled in by the agent-spawn site
 *  (EMD-27) once it lands; until then they're `None` for every
 *  event.
 */
export type AgentEvent = {
	agent: string,
	classifier: string,
	kind: AgentEventKind,
	message: string | null,
	/**
	 *  ISO-8601 UTC timestamp set at enrichment time. Stored as a
	 *  string at the wire boundary because specta requires a
	 *  dedicated feature flag to round-trip `chrono::DateTime`.
	 */
	timestamp: string,
	/**
	 *  Set by the agent-spawn site (EMD-27) when it injects the
	 *  hook env vars; `None` for raw events received before any
	 *  spawn integration.
	 */
	task_id: string | null,
	project_id: string | null,
};

export type AgentEventKind = 
/**  A normal in-flight notification (e.g. tool use, status message). */
{ kind: "notification"; notification_kind?: NotificationKind } | 
/**  Agent's session ended cleanly. */
{ kind: "stop" } | 
/**  Agent reported an error. */
{ kind: "error" } | 
/**
 *  Classifier didn't recognize the input; surfaces as an opaque
 *  pass-through so the renderer can still log it.
 */
{ kind: "unknown" };

export type NotificationKind = "general" | "permission_prompt" | "tool_use" | "status";

/**
 *  Projection of one row from the `projects` table that the renderer
 *  actually consumes. Mirror of the columns used in the v1 CRUD surface.
 *  Fields that exist in the schema but aren't needed yet
 *  (`workspace_provider`, `base_ref`, `ssh_connection_id`) are
 *  intentionally omitted — port them when a feature requires them.
 */
export type Project = {
	id: string,
	name: string,
	path: string,
	created_at: string,
	updated_at: string,
};

export type ProjectsCommandError = {
	/**  Stable machine-readable identifier; the renderer matches on this. */
	code: ProjectsErrorCode,
	/**  Human-readable hint. Surface to the user verbatim. */
	message: string,
};

export type ProjectsErrorCode = "empty_path" | "not_absolute" | "path_missing" | "path_not_directory" | "duplicate_path" | "not_found" | "storage";

export type PtyError = { kind: "not_found"; id: PtyId } | { kind: "spawn_failed"; message: string } | { kind: "io"; message: string };

export type PtyId = number;

export type PtySize = {
	rows: number,
	cols: number,
};

export type SecretsCommandError = {
	/**  Stable machine-readable identifier. Renderer matches on this. */
	code: SecretsErrorCode,
	/**  Human-readable hint. Surface this to the user verbatim. */
	message: string,
};

export type SecretsErrorCode = "keyring_unavailable" | "crypto" | "storage" | "invalid_value" | "unknown";

export type SpawnOptions = {
	command: string,
	args: string[],
	cwd: string | null,
	env: { [key in string]: string },
	size: PtySize,
};

export type UiMutationEvent = { kind: "project_created"; id: string } | { kind: "project_updated"; id: string } | { kind: "project_deleted"; id: string } | 
/**
 *  One classified agent-hook event (EMD-9). `task_id` is `None`
 *  until the agent-spawn site (EMD-27) injects coordinates.
 */
{ kind: "agent_hook_event"; task_id: string | null; event: AgentEvent };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

